{% set name = "duckdb-engine" %}
{% set package_name = name | replace("-", "_") %}
{% set version = "0.3.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ package_name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 824638a9326dc1ae9fcf586326c73449904b2a5b69a0da41c8b942f6ae0f75e7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - python-duckdb >=0.2.8
    - sqlalchemy >=1.3.19,<2
    - typing-extensions

test:
  requires:
    - pytest >=7,<8
    - hypothesis >=6.31.6,<7
    - pandas >=1,<2
    - ipython-sql
  imports:
    - duckdb_engine
  commands:
    # test_commit appears to be broken
    - pytest --pyargs duckdb_engine -k 'not test_commit and not test_simple_string'

about:
  home: https://github.com/Mause/duckdb_engine
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Very very very basic sqlalchemy driver for duckdb
  description: Very very very basic sqlalchemy driver for duckdb
  dev_url: https://github.com/Mause/duckdb_engine

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
